sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t dev-test-image ./client

script:
  - docker run -e CI=true dev-test-image npm test

after_success:
  - docker build -t eminmdzd/multi-client ./client
  - docker build -t eminmdzd/multi-server ./server
  - docker build -t eminmdzd/multi-worker ./worker
  - docker build -t eminmdzd/multi-nginx ./nginx

  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to dockerhub
  - docker push eminmdzd/multi-client
  - docker push eminmdzd/multi-server
  - docker push eminmdzd/multi-worker
  - docker push eminmdzd/multi-nginx


