sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t dev-test-image ./client

script:
  - docker run -e CI=true dev-test-image npm test

after_success:
  - docker build -t multi/client ./client
  - docker build -t multi/server ./server
  - docker build -t multi/worker ./worker
  - docker build -t multi/nginx ./nginx

  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to dockerhub
  - docker push multi/client
  - docker push multi/server
  - docker push multi/worker
  - docker push multi/nginx

  
